token: ${GH_TOKEN}
version_variable: mage/__init__.py:__version__
branch: main
upload_to_repository: false
upload_to_release: false
changelog_file: CHANGELOG.md
commit_message: "chore(release): {version} [skip ci]\n\n{changelog}"
post_release_hook: |
  echo "Building Docker image with tag: {version}"
  docker build -t ${DOCKER_REPO}:{version} .
  echo "Pushing Docker image to repository: ${DOCKER_REPO}"
  docker push ${DOCKER_REPO}:{version}