version: '3'
services:
  mage:
    image: mage
    container_name: mage 
    ports:
      - "6789:6789"
    volumes:
      - .:/home/mage_code
    environment:
    #To avoid adding too many variables here consider using
    #-.env instead where you define what variables you need
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENV: ${ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      KAFKA_SCHEMA_REGISTRY: ${KAFKA_SCHEMA_REGISTRY}
      SCHEMA_REGISTRY_USERNAME: ${SCHEMA_REGISTRY_USERNAME}
      SCHEMA_REGISTRY_PASSWORD: ${SCHEMA_REGISTRY_PASSWORD}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_CLIENT_ID_BATCH: ${KAFKA_CLIENT_ID_BATCH}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      KAFKA_GROUP_ID_BATCH: ${KAFKA_GROUP_ID_BATCH}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BATCH_TOPIC: ${KAFKA_BATCH_TOPIC}
      KAFKA_STREAM_TOPIC: ${KAFKA_STREAM_TOPIC}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
        
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data
  
volumes:
  minio_data:
