connector_type: kafka
bootstrap_server: "{{ env_var('KAFKA_BROKERS') }}"
topic: 'iot-telemetry'
include_metadata: false
api_version: 0.10.2
consumer_group: 'lambda_streaming_anomalies'
batch_size: 1 # consume one message at a time