name: Build Docker Image

# on:
#   workflow_call: # This enables it to be included by another workflow

on:
  push:
    branches:
      - main
      - 'release/*'

env:
  APP_NAME: "mage_projects" # Define the application name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release - Generate Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx -y -p @semantic-release/git -p @semantic-release/changelog -p @semantic-release/exec -p semantic-release@19 semantic-release
          RELEASE_VERSION=$(if [ -f /tmp/version ]; then cat /tmp/version | tr -d '[:space:]'; else echo "latest"; fi)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE_VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE_VERSION }} ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
