name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - 'release/*'

env:
  DOCKER_REPO: zefko/mage_projects  # Define your Docker repository name here

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --prefer-binary -r mage/requirements.txt

      - name: Log into Docker Registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Run Semantic Release and Build Docker Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
          DOCKER_REPO: ${{ env.DOCKER_REPO }}
        run: |
          semantic-release publish
