name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    env:
      DOCKERHUB_REPO: zefko/mage_projects   # Replace with your Docker Hub repo name
      IMAGE_NAME: mage_projects  # Use the same image name for GHCR
      REGISTRY: ghcr.io
      IMAGE_URL: ${{ github.repository }}  # This will be in the format 'username/repo'
      RELEASE: ${{ github.run_number }}     # Default to run number if not set

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release Setup
        run: |
          npx -y -p @semantic-release/git \
                 -p @semantic-release/changelog \
                 -p @semantic-release/exec \
                 -p semantic-release \
                 semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Release Variable
        id: set_release
        run: |
          if [ -f /tmp/version ]; then
            RELEASE=$(cat /tmp/version | tr -d '[:space:]')
          else
            RELEASE=${{ github.run_number }}
          fi
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "This is your release tag! $RELEASE"

      - name: Debug Variables
        run: |
          echo "DOCKERHUB_REPO: '$DOCKERHUB_REPO'"
          echo "RELEASE: '$RELEASE'"
          echo "IMAGE_URL: '$IMAGE_URL'"

      - name: Build and Push Docker Image to Docker Hub and GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.RELEASE }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_URL }}:${{ env.RELEASE }}
          platforms: linux/amd64,linux/arm64
