name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - 'release/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_REPO: zefko/mage_projects 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15'

      - name: Release Setup
        run: |
          npx -y -p @semantic-release/git -p @semantic-release/changelog -p @semantic-release/exec -p semantic-release@19 semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Release Variable
        id: set_release
        run: |
          if [ -f /tmp/version ]; then
            RELEASE=$(cat /tmp/version | tr -d '[:space:]')
          else
            RELEASE=${{ github.run_number }}
          fi
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "This is your release tag! $RELEASE"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:${RELEASE} .
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:${RELEASE}