name: Pre-Merge Tests

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mage/requirements.txt

      - name: Run unit tests
        run: make unit-tests
