name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - '*'  # Triggers on all pull request branches
  workflow_dispatch: # Allows manual triggering if needed

extends:
  template: ./scripts/PreBuild.yaml
