name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - '*'  # Triggers on all pull request branches
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  build_image:
    uses: ./scripts/PreBuild.yaml